### PR TITLE
Pass diskbus id to the kernel cmdline.

### PR DESCRIPTION
**Pull request by harishkrupo**

### CODE REVIEW

**Comment by harishkrupo** [comment]
@kalyankondapally @sgnanase

**Comment by harishkrupo** [comment]
This patch should be merged along with all these:
- android-ia/device-androidia-mixins#95
- android-ia/device-androidia#112
- android-ia/device-intel-common#10

**Comment by harishkrupo** [comment]
@sgnanase

**Comment by sgnanase** [comment]
Verified & Merged...

**Pull request merged**
