### PR TITLE
Squashfs for system and vendor images.

### PR DESCRIPTION
**Pull request by harishkrupo**
Compress system and vendor images using squashfs filesystem.

Jira: None
Test: Live and installed boot to home screen.

Signed-off-by: Harish Krupo <harish.krupo.kps@intel.com>

### CODE REVIEW

**Comment by harishkrupo** [comment]
@kalyankondapally @Kishore409 @sgnanase

**Comment by harishkrupo** [comment]
@tanminger Please review this. This helps bring the size of the final image from ~5GB to 700MB.

**Comment by tanminger** [comment]
The key point of images used in NUC is keep the image and its signature. So need to use dd to copy the whole image file to disk. As I know, we will use AVB to verify the partitions in Android O, and we have not tested using AVB to verify the squashfs images. If you want to have a test, please tell me the result :)
The reason of why we use ext4 instead of squashfs is for the end user, use ext4 can let the end user to change some files when debug some feature.

**Comment by harishkrupo** [comment]
yeah that is why i kept the dd and just squash(fs)ed the generated ext4 image. Then while installing mounted squash(fs)ed image and dd the ext4 image.

**Pull request merged**
