### PR TITLE
Add serial number to command line in grub

### PR DESCRIPTION
**Pull request by harishkrupo**
Serial number is required for adb to identify and name
the device

JIRA: AIA-254
Tests: Check if adb shows serial number in adb devices

Signed-off-by: Harish Krupo <harish.krupo.kps@intel.com>

### CODE REVIEW

**Comment by harishkrupo** [comment]
@shobhitka Could you check this and merge it?

**Comment by harishkrupo** [comment]
I have built dmidecode separately. Forgot to add that in there.

**Comment by harishkrupo** [comment]
@shobhitka added dmidecode.

**Comment by shobhitka** [comment]
Yeah will take this in for now. On analysis found that its not module param but init.cpp reads it and does some jugglery. For now we'll put this in installed grub cfg. Still serial number will not be available in live boot but installed images should be fine.

**Pull request merged**
