### PR TITLE
Add the support of using kernelflinger to boot in NUC.

### PR DESCRIPTION
**Pull request by tanminger**
JIRA: None.
Test: Test it in SKL NUC. Can boot to UI.

Signed-off-by: Ming Tan <ming.tan@intel.com>

### CODE REVIEW

**Comment by harishkrupo** [comment]
Gentle reminder: The option to ask for data partition size?

**Comment by tanminger** [comment]
The data partition size will be implemented in the feature. The following are still open:
1. Why the e2fsck need more than 4 minutes to check the /data.
2. Does the check of /data only once? If only once, then wait for 4 minutes maybe is accepted. When I debugged it in my NUC, in sometimes, it will check every time, but in other time, it only check it once. I want to wait for some days, maybe the system will be more stable.

**Comment by harishkrupo** [comment]
> Why the e2fsck need more than 4 minutes to check the /data.

Not sure about this. Maybe try on any linux systems with ext4 partition of that size?
>Does the check of /data only once? If only once, then wait for 4 minutes maybe is accepted. When I debugged it in my NUC, in sometimes, it will check every time, but in other time, it only check it once. I want to wait for some days, maybe the system will be more stable.

AFAIR, in traditional linux systems, running e2fsck is given in the 6th field in fstab. Android doesn't have the sixth field, instead i think it can be given as an option to vold (?). Need to check if such option is honoured by android's mounter (vold?).

**Comment by tanminger** [comment]
The NUC I used is using 1T SATA hd disk, not SSD.

**Comment by harishkrupo** [comment]
> The NUC I used is using 1T SATA hd disk, not SSD.

Not sure then.

**Comment by tanminger** [comment]
Update with https://github.com/android-ia/bootable-live-installer/pull/26.

**Comment by harishkrupo** [comment]
@tanminger FYI, you can also force push onto the same branch. It will update this PR. Opening a new one is not necessary. 
Anyways, it is your preference :)

**Pull request closed without merging**
